//4613732
var p2 = {
    title:"Even Fibonacci numbers",
    desc:'Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:<br />1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br />By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.',
    answer: function() {

        var sum = 0;
        var c = new Array(0, 1);

        while (c[0] < 4000000) {
            c.push(c[0] + c[1]);
            c.shift();
            if (c[0] % 2 == 0) sum += c[0];
        }

        return sum;
    }
};
